const express = require("express");
const router = express.Router();

const fs = require("node:fs");
const path = require("node:path");
const jwt = require("jsonwebtoken");
const userDB = require("../models/user");
const meter = require("../models/meter");
const dbConnector = require("../utils/duckdbConnector");

router.get("/", async (req, res) => {
  let connector;

  try {
    // Get token
    const token = req.headers.authorization?.split(" ")[1];

    if (!token) {
      return res.status(401).json({
        status: "error",
        message: "Unauthorized",
      });
    }

    // Verify JWT
    let decoded;
    try {
      decoded = jwt.verify(token, process.env.JWT_SECRET);
    } catch (jwtErr) {
      return res.status(401).json({
        status: "error",
        message: "Invalid or expired token",
      });
    }

    // Find user
    const user = await userDB.findById(decoded.id);

    if (!user) {
      return res.status(401).json({
        status: "error",
        message: "Unauthorized",
      });
    }

    // Find meters assigned to this supervisor
    const meters = await meter.find({
      supervisor: user._id,
    });

    const meterNumbers = meters.map((item) => String(item.meterNumber));

    // If supervisor has no meters
    if (meterNumbers.length === 0) {
      return res.status(200).json({
        status: "success",
        count: 0,
        data: [],
      });
    }

    // CSV file path
    const reportPath = path.resolve("./reports", "unmapped-report.csv");

    // Actually check whether the file exists on disk.
    // Note: on Render's default (non-persistent) disk, this file is
    // wiped on every restart/redeploy and must be regenerated by the
    // admin upload route before this endpoint will work again.
    if (!fs.existsSync(reportPath)) {
      return res.status(404).json({
        status: "error",
        message:
          "Report not found. Please ask the admin to regenerate the unmapped report.",
      });
    }

    connector = await dbConnector();

    // Create SQL IN list
    const meterNumberList = meterNumbers
      .map((number) => `'${number.replace(/'/g, "''")}'`)
      .join(", ");

    const safeReportPath = reportPath.replace(/'/g, "''");

    const query = `
      SELECT *
      FROM read_csv_auto('${safeReportPath}')
      WHERE CAST("MSN" AS VARCHAR) IN (${meterNumberList})
    `;

    // Run query and read results
    const reader = await connector.runAndReadAll(query);

    // Column names, in order — needed because getRowsJson() returns
    // arrays of values, not keyed objects
    const columnNames = reader.columnNames();

    // JSON-safe rows (handles BigInt, DECIMAL, DATE, etc. correctly)
    const rowsJson = reader.getRowsJson();

    // Map each row array -> object keyed by column name
    const data = rowsJson.map((row) =>
      Object.fromEntries(columnNames.map((col, i) => [col, row[i]])),
    );

    return res.status(200).json({
      status: "success",
      count: data.length,
      data,
    });
  } catch (error) {
    console.error("Error generating the report:", error);

    return res.status(500).json({
      status: "error",
      message: "Failed to generate the report",
    });
  } finally {
    // Always release the DuckDB connection, even on error,
    // so failed requests don't leak connections over time
    if (connector && typeof connector.close === "function") {
      try {
        await connector.close();
      } catch (closeErr) {
        console.error("Error closing DuckDB connector:", closeErr);
      }
    }
  }
});

module.exports = router;